### ISSUE TITLE
Blockscout Explorer returning Undefined for >10 min

### ISSUE THREAD

**Issue by Danibelle** [Giveth/GIVeconomy#335] opened 2021-12-17 17:38 UTC
Claimed, see tx confirmed in MetaMask but the link to Blockscout has not updated to show me a tx hash.

![image](https://user-images.githubusercontent.com/39466970/146585200-a60fb689-6577-4fde-b246-8554e3f6570a.png)
![image](https://user-images.githubusercontent.com/39466970/146585312-10eb2e9d-0ad4-4fce-95d6-7546b0a845be.png)

You can see the full screen shots of my testing process [here](https://docs.google.com/document/d/1Aqol2DHUUVcdX6hOYJVUWsDaS2ZkGfRBuuTMm5VgniI/edit?usp=sharing)!

**Comment by GriffGreen** [comment] 2021-12-18 02:46
Duplicate of #334

**Closed by GriffGreen** 2021-12-18 02:46 UTC
