### ISSUE TITLE
APR for uni v3 is not showing up

### ISSUE THREAD

**Issue by Zeptimus** [Giveth/GIVeconomy#280] opened 2021-12-14 21:49 UTC
![image](https://user-images.githubusercontent.com/74430951/146084744-686967ec-c06a-46d4-863e-6324efce0c5d.png)

@aminlatifi

**Comment by laurenluz** [comment] 2021-12-15 01:26
@aminlatifi I was with Zepti in this testing party and he was connected to Kovan, and kept refreshing the page and the APR wouldn't load for him. 

I couldn't repeat the same issue, on my side it was working fine, but I think there is something fishy

**Comment by divine-comedian** [comment] 2021-12-22 17:11
testing on staging - clean cache and cookies 

APR is showing up fine for me - I'm not able to reproduce this issue - looks to be resolved? moving to DONE
![image](https://user-images.githubusercontent.com/67759413/147129924-02fc0edf-e060-4b74-a53a-570ac3f6334e.png)

**Closed** 2021-12-23 03:09 UTC
