### ISSUE TITLE
The showing Unlock Date is wrong in Locked GIV details on OPTIMISM

### ISSUE THREAD

**Issue by maryjaf** [Giveth/GIVeconomy#886] opened 2023-09-12 18:38 UTC
based on @RamRamez's report this bug has been raised 
I'v locked some GIV on OPTIMISM for 4 round, the unlock date is shown 14 Nov but after locking in **Locked GIV Details** this date is shown 19 Nov

<img width="1298" alt="image" src="https://github.com/Giveth/GIVeconomy/assets/111529185/ecc1eaf4-8304-4bdb-a2b9-f07202a765d2">

<img width="754" alt="image" src="https://github.com/Giveth/GIVeconomy/assets/111529185/e07d2d9e-d942-40bb-8d87-92e5c29a788c">

@MohammadPCh @aminlatifi

**Comment by aminlatifi** [comment] 2023-09-12 20:00
The root cause is your position is not unlocked. I think the devops team has not deployed givpower-bot for staging env yet.
@mhmdksh

**Comment by maryjaf** [comment] 2023-09-13 05:43
> The root cause is your position is not unlocked. I think the devops team has not deployed givpower-bot for staging env yet. @mhmdksh

This problem happens on production

**Comment by MohammadPCh** [comment] 2023-09-13 06:35
@maryjaf hmm... let me check.

**Comment by maryjaf** [comment] 2023-09-18 15:26
> @maryjaf hmm... let me check.

Do we have any update about this bug on production? @MohammadPCh

**Comment by MohammadPCh** [comment] 2023-09-20 07:22
Thank you @maryjaf for reporting,
our rounds start and finish on Tuesdays. the number that we show in the lock modal, is calculated in the front-end and the number that we show in the locked GIV details is coming from the backend. Nov 14th is Tuesday but Nov 19th is not. so we need to check `unlockableAt` property in the backend.
@aminlatifi @mohammadranjbarz could you please take a look?

**Comment by aminlatifi** [comment] 2023-09-20 13:10
We made a mistake in deploying GIVpower on OP network. Its timing is not synced with production rounds and we have used the same value set on staging.
@divine-comedian

**Comment by aminlatifi** [comment] 2023-09-21 13:12
Merged subgraph to production, @maryjaf tested and is happy with it

**Closed as completed** 2023-09-25 13:45 UTC
Labels: bug
