### ISSUE TITLE
Fantom

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/GIVeconomy#771] opened 2022-11-03 11:42 UTC
https://fantom.foundation/blog/new-335m-ftm-incentive-program-with-gitcoin-grants/

**Comment by SnakeGH** [comment] 2022-11-16 07:20
Not sure why I am not able to assign myself to this in "assignees" but I will review this one

**Comment by SnakeGH** [comment] 2022-11-16 11:22
Research 

Fantom will participate in the immediate next Gitcoin Grants round in March 2022 (so the grant might be on hold) 

Will reach out to the below contact to confirm:  
•	Telegram - Melinoe at Fantom Foundation https://t.me/melinoe0x
Email - incentives@fantom.foundation & contact@fantom.foundation


Our Proposal Thoughts

So, the ask would be to add their chain "Opera" to our chain, similar to our proposal with Polygon. Also, since their token is doing well, we could also ask for a Liquidity Pool, as well as incentives users by offering tokens, if they donate using their tokens (FTM)

**Comment by divine-comedian** [comment] 2022-11-16 16:19
# GIVeconomy research notes

check to see if their grants are even active 
send them a pitch message 

Fantom is launching a gitcoin grants round that should be happening on their grants 2.0 platform
we know that there is interest in this avenue on opera network
see who is connected to that launch and if there is interest in Giveth

**Comment by SnakeGH** [comment] 2022-11-17 15:58
Good news, grant has been submitted. Thanks for all the assistance @spectoregia 

![image.png](https://images.zenhubusercontent.com/62a02df7985857d2501c4efc/0c5557f6-1489-4563-81bf-371b9598b325)

**Comment by Cotabe** [comment] 2022-11-23 02:41
GM @snakeGH this is very interesting. I have a couple of questions though...

1. Is the Grant program in Gitcoin quadratic funding? 
2. If so, is there another avenue for a more specific ask?

**Comment by SnakeGH** [comment] 2022-11-23 05:19
Thanks @Cotabe for the great questions:

1.) Yup, our application is now submitted, and it is part of a Gitcoin grant process
2.) I am not only in a broad telegram chat for high level updates / feedback but have the direct gate keepers telegram number too, so I have pushing her for more specific asks. If you have any, please send them my way :)

**Comment by SnakeGH** [comment] 2022-12-12 13:54
@spectoregia looks like voting is live now for the Fantom / Gitcoin Grants Round 1 and Giveth is listed :) 

https://grant-explorer.gitcoin.co/#/round/250/0xebdb4156203c8b35b7a7c6f320786b98e5ac67c3

**Comment by brichis** [comment] 2022-12-29 19:31
Hi everyone! You can follow our donations on Fantom here: 

https://docs.google.com/spreadsheets/d/1xgIjb9mXl87PuU5BqER0BoNRdtmZgcuva_3BcUmiTbo/edit?usp=sharing

**Comment by SnakeGH** [comment] 2023-01-09 08:31
voting / donating has closed, and funds will be transferred to Giveth wallet in coming weeks

**Comment by SnakeGH** [comment] 2023-03-12 11:22
@GriffGreen confirmed FTM in Giveth wallet, working on selling it. Closing issue as complete

**Closed by SnakeGH** 2023-03-12 11:22 UTC
Labels: Fundraising
