### ISSUE TITLE
The GIV $ values are all saying $0 :(

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#478] opened 2022-01-22 20:09 UTC
@MohammadPCh @aminlatifi can you look into this?

![image](https://user-images.githubusercontent.com/75490971/150653934-8a92f957-db91-4b99-8988-ffdb882df4f0.png)

**Comment by aminlatifi** [comment] 2022-01-23 11:01
@laurenluz  I cannot reproduce it on staging env

![image](https://user-images.githubusercontent.com/5684607/150675354-08e71477-23a3-4889-898b-d34f047227e3.png)

**Comment by aminlatifi** [comment] 2022-01-23 11:09
In production env also I modified the code to have a positive givback and I saw correct price value.

![image](https://user-images.githubusercontent.com/5684607/150675554-ef48aca5-032c-4ba5-849e-55119868d831.png)

**Comment by laurenluz** [comment] 2022-01-24 15:54
On production for me it is still showing $0:
![image](https://user-images.githubusercontent.com/75490971/150816871-f11de2e6-5740-4bc1-bc38-4fd976024c58.png)

And same on staging:
![image](https://user-images.githubusercontent.com/75490971/150817118-28f8bdac-fa2a-4b3b-bd07-fe108c071848.png)

**Comment by laurenluz** [comment] 2022-01-25 23:09
@aminlatifi this is still happening for Griff and Mitch, going to move it back

**Comment by aminlatifi** [comment] 2022-01-26 15:48
Should be fixed now!

**Comment by laurenluz** [comment] 2022-01-26 19:17
the $ value is showing up, but I think it's not being calculated right.. I thinkt my $ value should be more like $33 and $211 in this case. 

![image](https://user-images.githubusercontent.com/75490971/151230938-3546306f-9a79-42a5-9b7f-08b8fd1e5611.png)

from coingecko:
![image](https://user-images.githubusercontent.com/75490971/151231017-37374819-9c45-4463-b930-efc1c22bf63c.png)

**Comment by laurenluz** [comment] 2022-01-26 19:18
it's not sooo off, but having the amount show up as less than coingecko says is a small bummer. @aminlatifi 

is this because our GIV $ amount is a little delayed? GIV has been on the up...

**Comment by aminlatifi** [comment] 2022-01-26 20:13
> it's not sooo off, but having the amount show up as less than coingecko says is a small bummer. @aminlatifi
> 
> is this because our GIV $ amount is a little delayed? GIV has been on the up...

We use trace backend, it updates the price every one hour! I agree we need a more precise number. 
We may create a separate token service to serve impact-graph too, or have a separate backend for giveconomy to compute APRs and token price.

**Comment by aminlatifi** [comment] 2022-01-26 20:28
@laurenluz You are right, I did a mistake. It will be fixed in few minutes

**Comment by laurenluz** [comment] 2022-01-26 21:02
You da best @aminlatifi

**Closed** 2022-02-02 01:23 UTC
Labels: bug
